# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.1.2-3-g871a61a
_src_path: gh:epics-containers/services-template-compose
description: example IOC Instances and Services using docker compose
services: example
