services:

  me18x-ea-spump-01:
    container_name: me18x-ea-spump-01

    extends:
      service: linux_ioc
      file: ../../include/ioc.yml

    image: ghcr.io/diamondlightsource/fastcs-wpi-micro4:latest
    network_mode: "host"

    command: ["ioc", "me18x-ea-spump-01"]
    
    annotations:
      run.oci.keep_original_groups: "1"

    devices:
      - "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A10Q2NG8-if00-port0:/dev/ttyUSB0"
    
    stdin_open: true
    tty: true
    
    labels:
      version: 0.1.0

    environment:
      IOC_NAME: me18x-ea-spump-01

