# yaml-language-server: $schema=../../.helm-shared/values.schema.json

ioc-instance:
  image: ghcr.io/diamondlightsource/fastcs-wpi-micro4:latest
  args:
    - stdio-socket --ptty "fastcs-wpi-micro4 run /epics/ioc/config/controller.yaml"

  # DO NOT use the default livenessProbe and preStop from ioc-instance.
  # Leave blank or provide a path to an executable inside the container image.
  livenessExecutable: ""
  preStopExecutable: ""

